/*
 * This source file was generated by the Gradle 'init' task
 */
package gem2gem;


import static gem2gem.Game.*;

public class App {
    public static void main(String[] args) {
        Game game = new Game();
        game.start(); //Facade
    }
}
